name: Build and Push via Master

on:
  push:
    branches:    
      - master

jobs:
  test_build_and_push_to_docker_registry:
    name: Test, build and publish image to docker hub
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v3
      with:
        node-version: '18.x'
    - name: Install dependencies
      run: npm install && npm run postinstall
    - name: Unit tests
      run: npm run test
    - name: Docker login
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_ACCESS_TOKEN}}
      run: |
        echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - name: Docker build and tag image
      run: docker build . --file Dockerfile --tag xinfinorg/xdc-relayer:latest
    - name: Docker push
      run: docker push xinfinorg/xdc-relayer:latest