name: CI

on:
  pull_request:
    branches:    
      - master
  push:
    branches:    
      - master

jobs:
  build:
    name: Build the project
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install dependencies
      run: npm ci
    - name: Building the project
      run: npm run build
    - name: Unit tests
      run: npm run test