name: CI

on:
  pull_request:
    branches:    
      - master
  push:
    branches:    
      - master

jobs:
  build:
    name: Build the project
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v1
      with:
        node-version: '18.x'
    - name: Install dependencies
      run: npm install && npm run postinstall
    - name: Unit tests
      run: npm run test