name: PR tests
on:
  pull_request:
    branches:    
      - master
  
jobs:
  test_on_pr:
    name: Run tests on PR
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v3
      with:
        node-version: '18.x'
    - name: Install dependencies
      run: npm install && npm run postinstall
    - name: Unit tests
      run: npm run test